name: run test of feature branch

on:
  push:
    branches:
      'feature/*'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4 libxss1 libappindicator1 libindicator7
          sudo apt-get install -y fonts-liberation xdg-utils libu2f-udev
          sudo apt-get install -y wget unzip

      - name: Download ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /home/runner/bin/
          rm chromedriver_linux64.zip
          sudo mv /home/runner/bin/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run sign_in test
        run: mvn test
