name: run unit tests of feature branches

on:
  push:
    branches: 
      'feature/*'


jobs:
  run-unit-test:
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0


      - name: run build
        run: mvn clean install
